application: odeskreports
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: static/css

- url: /images
  static_dir: static/images

- url: /js
  static_dir: static/js

- url: /company_selector
  static_files: static/test/test.CompanySelector.html
  upload: static/test/test.CompanySelector.html

- url: /.*
  script: main.py