application: timetrackercallback
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: static/reports_home.html
  upload: static/reports_home.html

- url: /reports_home.html
  static_files: static/reports_home.html
  upload: static/reports_home.html

- url: /weekly_company_timesheet
  static_files: static/weekly_company_timesheet.html
  upload: static/weekly_company_timesheet.html

- url: /weekly_company_timesheet.html
  static_files: static/weekly_company_timesheet.html
  upload: static/weekly_company_timesheet.html

- url: /monthly_provider_timesheet
  static_files: static/monthly_provider_timesheet.html
  upload: static/monthly_provider_timesheet.html

- url: /monthly_provider_timesheet.html
  static_files: static/monthly_provider_timesheet.html
  upload: static/monthly_provider_timesheet.html

- url: /task_summary_report.html
  static_files: static/task_summary_report.html
  upload: static/task_summary_report.html

- url: /task_summary_report
  static_files: static/task_summary_report.html
  upload: static/task_summary_report.html

- url: /provider_work_summary.html
  static_files: static/provider_work_summary.html
  upload: static/provider_work_summary.html

- url: /provider_work_summary
  static_files: static/provider_work_summary.html
  upload: static/provider_work_summary.html

- url: /timesheet_details.html
  static_files: static/timesheet_details.html
  upload: static/timesheet_details.html

- url: /timesheet_details
  static_files: static/timesheet_details.html
  upload: static/timesheet_details.html

- url: /my_weekly_timesheet
  static_files: static/my_weekly_timesheet.html
  upload: static/my_weekly_timesheet.html

- url: /my_weekly_timesheet.html
  static_files: static/my_weekly_timesheet.html
  upload: static/my_weekly_timesheet.html

- url: /weekly_company_timesheet_provider.html
  static_files: static/weekly_company_timesheet_provider.html
  upload: static/weekly_company_timesheet_provider.html

- url: /weekly_company_timesheet_provider
  static_files: static/weekly_company_timesheet_provider.html
  upload: static/weekly_company_timesheet_provider.html

- url: /weekly_company_timesheet_buyer.html
  static_files: static/weekly_company_timesheet_buyer.html
  upload: static/weekly_company_timesheet_buyer.html

- url: /weekly_company_timesheet_buyer.html
  static_files: static/weekly_company_timesheet_buyer.html
  upload: static/weekly_company_timesheet_buyer.html

- url: /css
  static_dir: static/css

- url: /images
  static_dir: static/images

- url: /js
  static_dir: static/js

- url: /company_selector
  static_files: static/test/test.CompanySelector.html
  upload: static/test/test.CompanySelector.html

- url: /urlparameters
  static_files: static/test/timesheet_detail_parameters.html
  upload: static/test/timesheet_detail_parameters.html