application: timetrackercallback
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: static/timereports.html
  upload: static/timereports.html
  
- url: /css
  static_dir: static/css
  
- url: /js
  static_dir: static/js  
