application: timetrackercallback
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: static/reports_home.html
  upload: static/reports_home.html

- url: /reports_home.html
  static_files: static/reports_home.html
  upload: static/reports_home.html

- url: /weekly_company_timesheet
  static_files: static/weekly_company_timesheet.html
  upload: static/weekly_company_timesheet.html

- url: /weekly_company_timesheet.html
  static_files: static/weekly_company_timesheet.html
  upload: static/weekly_company_timesheet.html

- url: /monthly_provider_timesheet
  static_files: static/monthly_provider_timesheet.html
  upload: static/monthly_provider_timesheet.html

- url: /monthly_provider_timesheet.html
  static_files: static/monthly_provider_timesheet.html
   upload: static/monthly_provider_timesheet.html

- url: /company_selector
  static_files: static/test/test.CompanySelector.html
  upload: static/test/test.CompanySelector.html

- url: /task_summary_report.html
  static_files: static/task_summary_report.html
  upload: static/task_summary_report.html

- url: /task_summary_report
  static_files: static/task_summary_report.html
  upload: static/task_summary_report.html

- url: /provider_weekly
  static_files: static/provider_weekly_report.html
  upload: static/provider_weekly_report.html

- url: /provider_weekly_report.html
  static_files: static/provider_weekly_report.html
  upload: static/provider_weekly_report.html

- url: /agency_report.html
  static_files: static/agency_report.html
  upload: static/agency_report.html

- url: /agency_report
  static_files: static/agency_report.html
  upload: static/agency_report.html

- url: /agency_buyer_report.html
  static_files: static/agency_buyer_report.html
  upload: static/agency_buyer_report.html

- url: /agency_buyer_report
  static_files: static/agency_buyer_report.html
  upload: static/agency_buyer_report.html

- url: /css
  static_dir: static/css

- url: /images
  static_dir: static/images

- url: /js
  static_dir: static/js
